"""Deterministic fictional provenance demonstration, with no model execution."""

import hashlib
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4

from .graph import EVENT_ADAPTER, append_events
from .schemas import GraphEvent, LogEvent

SOURCE = (
    "FICTIONAL SOFTWARE FIXTURE: no real interviews or research.\n"
    "Earlier planning note: all library workshops are on weekday evenings.\n"
    "Later corrected timetable: one workshop meets on Saturday mornings.\n"
)


def demo_events(run_id: str) -> tuple[list[GraphEvent], list[GraphEvent]]:
    """Build a fixed scenario with separate initial and correction batches.

    Reviewer and agent identities are simulated. The correction is predefined,
    not inferred by code or generated by a model.
    """
    events = []

    def add(event_type: str, subject: str, payload: dict) -> None:
        events.append(
            EVENT_ADAPTER.validate_python(
                {
                    "event_id": f"{run_id}:event_{len(events) + 1}",
                    "run_id": run_id,
                    "timestamp": datetime.now(timezone.utc),
                    "subject_id": subject,
                    "source_agent_id": "sovereign_synthesizer",
                    "exercise_id": "secondary_research",
                    "event_type": event_type,
                    "payload": payload,
                }
            )
        )

    for source_id, line in (("planning_note", 2), ("corrected_timetable", 3)):
        add(
            "evidence_added",
            source_id,
            {
                "source_id": source_id,
                "source_path": "fixture:provenance_demo_timetable",
                "snapshot": SOURCE,
                "content_sha256": hashlib.sha256(SOURCE.encode("utf-8")).hexdigest(),
                "start_line": line,
                "end_line": line,
            },
        )
    for claim_id, text, source_id in (
        ("evenings_only", "All workshops meet on weekday evenings.", "planning_note"),
        (
            "weekend_session",
            "One workshop meets on Saturday mornings.",
            "corrected_timetable",
        ),
    ):
        add(
            "claim_added",
            claim_id,
            {
                "takeaway_id": claim_id,
                "exercise_id": "secondary_research",
                "agent_id": "operational_realist",
                "claim": text,
                "claim_type": "observation",
                "evidence_refs": [source_id],
                "confidence": 0.7,
                "validation_status": "proposed",
                "public_reasoning_summary": "Restates the assigned fictional source.",
                "open_questions": [],
            },
        )
        add(
            "status_changed",
            claim_id,
            {
                "status": "supported",
                "evidence_refs": [source_id],
                "public_reasoning_summary": "Supported by fictional evidence only.",
            },
        )
        add(
            "review_recorded",
            claim_id,
            {
                "decision": "accepted",
                "reviewer_id": "simulated_tutorial_reviewer",
                "public_reasoning_summary": "Simulated review for the tutorial.",
            },
        )
    add(
        "edge_added",
        "schedule_conflict",
        {
            "source_id": "weekend_session",
            "target_id": "evenings_only",
            "relation": "contradicts",
            "public_reasoning_summary": "Saturday contradicts evenings-only.",
        },
    )
    add(
        "status_changed",
        "evenings_only",
        {
            "status": "contested",
            "evidence_refs": ["corrected_timetable"],
            "public_reasoning_summary": "The timetable challenges the note.",
        },
    )
    boundary = len(events)
    add(
        "edge_added",
        "schedule_correction",
        {
            "source_id": "weekend_session",
            "target_id": "evenings_only",
            "relation": "invalidates",
            "public_reasoning_summary": "The fixture labels this a correction.",
        },
    )
    add(
        "status_changed",
        "evenings_only",
        {
            "status": "deprecated",
            "evidence_refs": ["corrected_timetable"],
            "public_reasoning_summary": "Retain history; exclude the old claim.",
        },
    )
    return events[:boundary], events[boundary:]


def run_demo(graph_root: Path, log_root: Path) -> Path:
    """Append a fresh demo history and print its evidence trail and correction."""
    run_id = f"demo-{uuid4().hex}"
    graph_path = graph_root / run_id / "provenance_events.jsonl"
    log_path = log_root / run_id / "run_events.jsonl"
    initial, correction = demo_events(run_id)
    state = append_events(graph_path, initial)
    print(
        "FICTIONAL demonstration: no models, real research, or actual human approval."
    )
    print(f"Before correction: evenings_only = {state.statuses['evenings_only']}")
    history_before = graph_path.read_bytes()
    state = append_events(graph_path, correction)
    print(f"After correction: evenings_only = {state.statuses['evenings_only']}")
    print(
        "Original history preserved: "
        f"{graph_path.read_bytes().startswith(history_before)}"
    )
    print(
        f"Claims retained: {len(state.claims)}; "
        f"reportable: {len(state.reportable_claims())}"
    )
    for claim in state.reportable_claims():
        print(f"\n[{claim.takeaway_id}] {claim.claim}")
        print(
            f"Type: {claim.claim_type}; status: {state.statuses[claim.takeaway_id]}; "
            f"review: {state.reviews[claim.takeaway_id]} (simulated)"
        )
        for source_id in claim.evidence_refs:
            source = state.evidence[source_id]
            excerpt = "\n".join(
                source.snapshot.splitlines()[source.start_line - 1 : source.end_line]
            )
            print(f"Source: {source_id}, {source.source_path}:{source.start_line}")
            print(f"Excerpt: {excerpt}")
            print(f"SHA-256: {source.content_sha256}")
    log = LogEvent(
        run_id=run_id,
        timestamp=datetime.now(timezone.utc),
        stage_id="provenance_demo",
        exercise_id="secondary_research",
        agent_id="fixture_driver",
        event_type="demo_completed",
        input_manifest=["fixture:provenance_demo_timetable"],
        output_manifest=[str(graph_path)],
        graph_event_ids=[event.event_id for event in initial + correction],
        public_reasoning_summary="Appended a fixture correction and replayed history.",
        warnings=["All evidence, decisions, and agent attribution are simulated."],
        validation_status="completed",
    )
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("a", encoding="utf-8") as stream:
        stream.write(log.model_dump_json() + "\n")
    print(f"\nHistory: {graph_path}\nLog: {log_path}")
    return graph_path
